### ISSUE TITLE
Enable GitHub Pages?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#1]
It'd be super if this spec were available at https://w3c.github.io/annotation-aria/

Bonus points if it's also set as the homepage of this repo (see "edit" next to repo description).

Thanks!
🎩

**Comment by jnurthen** [comment]
I believe @michael-n-cooper is the only one with permissions to do this.

**Comment by BigBlueHat** [comment]
For now: https://raw.githack.com/w3c/annotation-aria/master/index.html

**Comment by michael-n-cooper** [comment]
This is set up now with automatic build on pushes to master branch.
