### ISSUE TITLE
Update `<ins>`/`<del>` section to point to new insertion/deletion roles

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#3]
See https://w3c.github.io/aria/#insertion and https://w3c.github.io/aria/#deletion

These roles were/are being discussed in https://github.com/w3c/aria/issues/526

**Comment by aleventhal** [comment]
Looks like this was done, although all the links labelled "insertion and/or deletion" seem to be broken.

**Comment by BigBlueHat** [comment]
Yep. Content fixed earlier. References fixed in https://github.com/w3c/annotation-aria/commit/4c12ea9fbb8a591ce011f9c779f28f4208022ff3 ...still waiting on the bot to update the gh-pages branch, though...

Closing 'cause this is fixed. Reopen if you think I missed something.
