### ISSUE TITLE
Consider a different name for `annotation-attribution`

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#4]
From @mcking65:
> we may want to choose a better name as this name may ultimately just be used by screen readers and most users might not know what to make of it.

**Comment by aleventhal** [comment]
See also issue #5, where we are considering merging attribution with revision.

**Comment by BigBlueHat** [comment]
Does this example make the use case and term choice clearer?
https://w3c.github.io/annotation-aria/#annotation-attribution
