### ISSUE TITLE
Remove `annotation-attribution` in favor of using `annotation-revision`

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#5]
From @aleventhal:
> recommend we make this redundant with `annotation-revision`, and remove this one.

**Comment by BigBlueHat** [comment]
@aleventhal I'd love to hear more about this one, as I couldn't sort out how `attribution` would be redundant with `revision`. Maybe it's a wiki content error? See "TBD#2" on the [wiki page](https://github.com/w3c/aria/wiki/ARIA-annotations-draft-proposal/8b9157e057473c3a5da579f959346af2e34f9963#roles-for-annotation-purposes).

**Comment by aleventhal** [comment]
@BigBlueHat I think of attribution as describing who wrote some content, perhaps with a time/date stamp or other metadata. But, I also think a revision as the same thing.

For example 
```<span aria-details="annotation-1>Cats are liquid</span>```
```<div id="annotation-1" role="annotation-attribution">Added by Aaron<br> April 1, 2019</div>```
vs.
```<div id="annotation-1" role="annotation-revision">Added by Aaron<br> April 1, 2019</div>```

How do you imagine them being used?

**Comment by 23001900** [comment]
<div id="annotation-1" role="annotation-revision">Added by Aaron<br> April 1, 2019</div

**Comment by BigBlueHat** [comment]
@aleventhal I was thinking more along the lines of photo/quote attribution--rather than stating who did something in a change log (though that's obviously also attribution.

Some thing more like:
```html
<span aria-details="annotation-1>Cats are liquid</span>
<div id="annotation-1" role="annotation-attribution">@aleventhal</div>
```
vs.
```html
<span aria-details="annotation-1>Cats are liquid</span>
<div id="annotation-1" role="annotation-revision">Added by Aaron<br> April 1, 2019</div>
```

My concern is that developers won't see "revision" as encompassing "attribution"--which could simply be a statement of provenance presented "secondarily" (as an annotation) vs. within the primary content.

Thoughts?

**Comment by aleventhal** [comment]
I think we should bring this issue to the wider group. I'm not going to lose sleep either way. I see your point that it might be easier for developers to pick the right one if they have both, even though they are very close in meaning.

**Comment by BigBlueHat** [comment]
There are examples which hopefully highlight their differences now. See https://w3c.github.io/annotation-aria/#annotation-attribution vs. https://w3c.github.io/annotation-aria/#annotation-revision
