### ISSUE TITLE
Should `annotation-suggestion`/`annotation-revision` processing ignore additional markup?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#7]
Right now, we define (somewhat implicitly...) how `<ins>`/`<del>` could be processed by AT into actual edits in the main text (i.e. replacing the annotated content following the logic expressed via `<ins>` and/or `<del>`).

Should we also add something about how to handle any other markup? I'd suggest we state that it should be thrown out entirely--but want to make sure that's what would be expected here from an AT perspective (and that there aren't hidden "gotchas" I've not yet thought about).

**Comment by aleventhal** [comment]
How about, anything not wrapped in ins/del is technically an error, but can be treated by the UA/AT as an insertion.

**Comment by BigBlueHat** [comment]
So...
```html
<p>I started writing this<mark aria-details="revision-123"> morning.</mark></p>
...
<div id="revision-123" role="annotation-revision">
Added at <time datetime="2019-07-31T09:15">9:15 am</time> by @BigBlueHat
</div>
```

Essentially, assuming insertion is the default?
