### ISSUE TITLE
Beyond HTML?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/annotation-aria#9]
We state "HTML...tag" in a few places, but that's generally in relation to `<ins>` and `<del>`. I've begun making sure all of those references also state that these could be represented with alternate markup and `role="insertion"` or `role="deletion"`.

Should I go farther and remove the reference to `<ins>`/`<del>` or perhaps flip the order and use `<ins>`/`<del>` as exemplary of markup that include these roles as defaults?

**Comment by jnurthen** [comment]
Don't we really mean element not tag?
HTML tag -> element
`<ins>` or `<del>` tag -> [HTML] `<ins>` or `<del>` element

**Comment by BigBlueHat** [comment]
Probably. 😉 Bigger question is if this is somehow to HTML-y currently, and if it needs rewording.

I can certainly s/tag/element.

**Comment by jnurthen** [comment]
but yeah - where you have HTML tag I think you can just use element

Where you have specific HTML elements referenced we should state [HTML] `<del>` to auto-generate the reference to the HTML spec and be more specific.

I don't care which order they are in.....

**Comment by jnurthen** [comment]
i.e.
```
The annotated content of such a change-related annotation MUST contain at least one HTML 
<ins> or <del> tag or at least one HTML tag with a role value of either insertion or deletion defined 
in [wai-aria-1.2].
```

would read
```
The annotated content of such a change-related annotation MUST contain at least one [HTML] 
<ins> or <del> element or at least one element with a role value of either insertion or deletion 
defined in [wai-aria-1.2].
```
